### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#298]
This issue is to collect performance-related tasks:

- [x] https://github.com/cevo-public/LAPIS/issues/12
- [ ] https://github.com/cevo-public/LAPIS/issues/11
- [x] https://github.com/cevo-public/cov-spectrum-server/issues/26
- [x] #299
- [x] #300
- [x] #301
- [x] #332
- [x] https://github.com/cevo-public/LAPIS/issues/14
- [x] https://github.com/cevo-public/LAPIS/issues/18
- [x] https://github.com/cevo-public/LAPIS/issues/22

Pain reports:

- #333

**Comment by corneliusroemer** [comment]
Does #300 fit in here?
