### ISSUE TITLE
Experiment the selection method of multiple variants for comparison

### ISSUE THREAD

**Issue by ningxie1991** [GenSpectrum/cov-spectrum-website#309]
Related to #175

### ToDo

1. Add multiple variants to the url
Some options:
    1. `/explore/Switzerland/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*&aaMutations=N%3AR203K&pangoLineage=B.1.1.112&pangoLineage=B.1.617.2*&pangoLineage=N.10&aaMutations=N%3AM1X&pangoLineage=P.1.17.1`
    2. `/explore/Switzerland/AllSamples/Past6M?variants=%5B%7B%22aaMutations%22%3A%5B%22N%3AR203K%22%2C%22N%3AS235F%22%5D%2C%22pangoLineage%22%3A%22B.1.1.529*%22%7D%2C%7B%22pangoLineage%22%3A%22B.1.617.2*%22%7D%5D`
    Option i is most straightforward but not good for parsing different variants with various combination of properties. Option ii is encoding the whole list/array of variants as they are.

    Suggestion:
    We encode the array of variants.
    Current url param encoding implementation only works for one variant. 
    https://github.com/cevo-public/cov-spectrum-website/blob/6093a9d180ec42e4218d8b3870fcfe17aba778f5/src/data/VariantSelector.ts#L22-L35
If we use JSON.stringify, we don't need to manually check if a property is undefined or not. 
```
const variants = [{
  aaMutations: ['N:R203K', 'N:S235F'],
  gisaidClade: undefined,
  nextstrainClade: undefined,
  nucMutations: undefined,
  pangoLineage: "B.1.1.529*",
  variantQuery: undefined
}, {
  aaMutations: [],
  gisaidClade: undefined,
  nextstrainClade: undefined,
  nucMutations: undefined,
  pangoLineage: "B.1.617.2*",
  variantQuery: undefined
}]
console.log(JSON.stringify(variants))

const filteredVariants= JSON.stringify(variants.map(function(selector) {
    if (selector.aaMutations?.length == 0) {
      selector.aaMutations = undefined
    }
    if (selector.nucMutations?.length == 0) {
      selector.nucMutations = undefined
    }
    return selector;
  }));

const params = new URLSearchParams()
params.set("variants", JSON.stringify(filteredVariants))
console.log(params.toString())

const query = new URLSearchParams(params)
console.log(JSON.parse(query.get("variants")))

Output:
> '[{"aaMutations":["N:R203K","N:S235F"],"pangoLineage":"B.1.1.529*"},{"aaMutations":[],"pangoLineage":"B.1.617.2*"}]'
> "variants=%22%5B%7B%5C%22aaMutations%5C%22%3A%5B%5C%22N%3AR203K%5C%22%2C%5C%22N%3AS235F%5C%22%5D%2C%5C%22pangoLineage%5C%22%3A%5C%22B.1.1.529*%5C%22%7D%2C%7B%5C%22pangoLineage%5C%22%3A%5C%22B.1.617.2*%5C%22%7D%5D%22"
> '[{"aaMutations":["N:R203K","N:S235F"],"pangoLineage":"B.1.1.529*"},{"pangoLineage":"B.1.617.2*"}]'
```

2. Keep a list of variants
Currently, the code is written for displaying one Pango or variant only. The implementation now does not work well with multiple Pango or variants. 
Current implementation:
    1. Click on a variant card in the preview / search for a variant 
    2. Calls explore-url.ts script to update the url
    3. Use URLSearchParams to query the url for any variants 
   https://github.com/cevo-public/cov-spectrum-website/blob/6093a9d180ec42e4218d8b3870fcfe17aba778f5/src/helpers/explore-url.ts#L180-L195
    Then we return the found variant back to the ExploreFocusSplit page.
    We need to maintain a list where we can add and remove items. 
    Suggestion:
    We keep the list in  explore-url to set the url query string. We also need to modify the code in ExploreFocusSplit to keep dataset for multiple variants. 
    The current implementation searches for on selector at a time. Shall we create an API for multi-selecors query?
https://github.com/cevo-public/cov-spectrum-website/blob/6093a9d180ec42e4218d8b3870fcfe17aba778f5/src/pages/ExploreFocusSplit.tsx#L49-L61
     We could write a `useQueries` hook to execute parallel queries or another API that takes an array of variant selectors as input.

3. Focus page needs to show data for multiple variants
    Suggestion:
    We can keep the Explore panel functions mostly, just by adding an "Add" button to the search input, so we can use the same search box to add variants to the list. Also, we will add multi select on the preview grid, so user can select multiple mini charts to see comparison.

**Comment by chaoran-chen** [comment]
Hi @ningxie1991, sorry for the late response! I forgot the issue here...

- I like the idea of the toggle, but I would rather put it closer to the search. Just changing the toggle shouldn't change anything as long as the user does not put in another variant to compare to.
- The user should be able to compare more than two variants with each other. In the current discussion, it would be very useful to compare a whole bunch of Delta sublineages. Pair-wise comparisons are not enough.
- Maybe just leave the data range picker where it is, i.e., at the top of the right panel?

**Comment by ningxie1991** [comment]
Example url with comparison:
https://outbreak.info/compare-lineages?pango=Delta&pango=Omicron&pango=Alpha&pango=Beta&pango=Gamma&gene=ORF1a&gene=ORF1b&gene=S&threshold=75&nthresh=1&sub=false&dark=true

**Comment by ningxie1991** [comment]
@chaoran-chen I added my research and conclusion for the explore url and data needed for the multiple variants selection in the description of this issue. After some thought, I think we should keep the left explore panel as they are, because adding additional search input boxes just for adding more variants doesn't look good to me. We can simply just have an "Add" button to add the selected variant from the search bar to the "list" which we will create and maintain. And for the preview, we can simply enable user to select multiple mini charts. I will code up something.

**Comment by ningxie1991** [comment]
- [x] Prettify the url: variants?pangoLineage0=B.1.1.7&aaMutations1=S:501Y&pangoLineage1=B.1.351
- [ ] Add a hook for parallel queries
- [x] Move search bar to the Focus page and have compare mode + single mode
- [x] Compare mode: Add button to add variant to a list in focus page
- [x] Single mode: Search button to search single variant

**Comment by chaoran-chen** [comment]
Hi @ningxie1991, thank you very much for the work that you have done on this topic! As you are leaving our team, I will take over the task :)

**Comment by ningxie1991** [comment]
> Hi @ningxie1991, thank you very much for the work that you have done on this topic! As you are leaving our team, I will take over the task :)

@chaoran-chen , most of the ideas are in the #373 pull request for your reference. Thank you!
Preview: https://cov-spectrum-develop-e92lvok8f-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*
