### ISSUE TITLE
Custom settings

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/cov-spectrum-website#341]
We have a number of issues related to custom user settings:

- [x] GenSpectrum/cov-spectrum-website#95
- [x] GenSpectrum/cov-spectrum-website#190
- [ ] GenSpectrum/dashboards#63
- [ ] GenSpectrum/cov-spectrum-website#318
- [ ] GenSpectrum/cov-spectrum-website#338
- [ ] GenSpectrum/cov-spectrum-website#468
